# 2do Entregable del Reto
## Selección, Configuración y entrenamiento del modelo

Carga de librerías

In [28]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb






Importamos los datos

In [29]:
df= pd.read_csv('Titanic_train_test.csv')


Separamos los datos de test y train

In [30]:
df=df.drop(columns='Unnamed: 0')

In [31]:
dftrain=df.iloc[:891]
dftest=df.iloc[891:]

In [32]:
dftest=dftest.drop(columns=['Survived'])

Separamos en target y features

In [33]:
y=dftrain['Survived']

In [34]:
X=dftrain.drop(columns='Survived')

Escalamos los features

In [35]:
scaler=StandardScaler()
Xf=scaler.fit_transform(X)

In [36]:
Xf

array([[ 0.82737724, -0.54234313,  0.05915988, ...,  0.61583843,
        -0.73769513,  0.73769513],
       [-1.56610693,  0.59598827,  0.05915988, ..., -1.62380254,
         1.35557354, -1.35557354],
       [ 0.82737724, -0.25776028, -0.56097483, ...,  0.61583843,
         1.35557354, -1.35557354],
       ...,
       [ 0.82737724, -0.6490617 ,  1.29942929, ...,  0.61583843,
         1.35557354, -1.35557354],
       [-1.56610693, -0.25776028, -0.56097483, ..., -1.62380254,
        -0.73769513,  0.73769513],
       [ 0.82737724,  0.169114  , -0.56097483, ..., -1.62380254,
        -0.73769513,  0.73769513]])

Separación del train a train y set

In [37]:
X_train, X_test, y_train, y_test = train_test_split(Xf, y, test_size=0.2, random_state=42)#


#### Regresión Logística

In [38]:
modelo_RL = LogisticRegression(dual=True, class_weight='balanced', solver='liblinear') #Modelo de regresi'on Logistica
modelo_RL.fit(X_train, y_train)#Entrenamiento del modelo 
y_predRL = modelo_RL.predict(X_test)#Predicciones de los datos de prueba

In [39]:
accuracy = accuracy_score(y_test, y_predRL)
f1 = f1_score(y_test, y_predRL)
roc_auc = roc_auc_score(y_test, y_predRL)
conf_matrix = confusion_matrix(y_test, y_predRL)

print(f'Accuracy: {accuracy}')
print(f'F1 Score: {f1}')
print(f'ROC-AUC: {roc_auc}')
print('Confusion Matrix:')
print(conf_matrix)


Accuracy: 0.8156424581005587
F1 Score: 0.7898089171974523
ROC-AUC: 0.818918918918919
Confusion Matrix:
[[84 21]
 [12 62]]


#### Support Vector Machine

In [40]:
X_train, X_test, y_train, y_test = train_test_split(Xf, y, test_size=0.2, random_state=42)#

In [41]:
modelo_SVC = SVC(C=10, gamma=0.1, probability=True, class_weight='balanced')
modelo_SVC.fit(X_train,y_train)
y_predSV = modelo_SVC.predict(X_test)

In [42]:
accuracy = accuracy_score(y_test, y_predSV)
f1 = f1_score(y_test, y_predSV)
roc_auc = roc_auc_score(y_test, y_predSV)
conf_matrix = confusion_matrix(y_test, y_predSV)

print(f'Accuracy: {accuracy}')
print(f'F1 Score: {f1}')
print(f'ROC-AUC: {roc_auc}')
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.8044692737430168
F1 Score: 0.7770700636942676
ROC-AUC: 0.8074002574002573
Confusion Matrix:
[[83 22]
 [13 61]]


#### Red Neuronal

In [43]:
X_train, X_test, y_train, y_test = train_test_split(Xf, y, test_size=0.2, random_state=42)#

In [44]:
"""net=MLPClassifier(hidden_layer_sizes=(64,64,128,128,128,128,64,64),
 activation='relu', solver='sgd', alpha=0.0001,
 batch_size='auto', learning_rate='adaptive',
 learning_rate_init=0.001, power_t=0.5, max_iter=5000,
 shuffle=True, random_state=None, tol=0.0001,
 verbose=False, warm_start=False, momentum=0.9,
 nesterovs_momentum=True, early_stopping=False,
 validation_fraction=0.1, beta_1=0.9, beta_2=0.999,
 epsilon=1e-08, n_iter_no_change=50, max_fun=15000)"""
net = MLPClassifier(hidden_layer_sizes=(128, 128), solver='adam', learning_rate_init=0.01, max_iter=1000)


In [45]:
#Entrenamiento
net.fit(X_train, y_train)
print("Done ")

Done 


In [46]:
# 4. evaluate model
acc_train = net.score(X_train, y_train)
print("Accuracy on train = %0.4f " % acc_train)
acc_test = net.score(X_test, y_test)
print("Accuracy on test = %0.4f " % acc_test)

Accuracy on train = 0.8680 
Accuracy on test = 0.7765 


In [47]:
y_predNET = net.predict(X_test)
accuracy = accuracy_score(y_test, y_predNET)
f1 = f1_score(y_test, y_predNET)
roc_auc = roc_auc_score(y_test, y_predNET)
conf_matrix = confusion_matrix(y_test, y_predNET)

print(f'Accuracy: {accuracy}')
print(f'F1 Score: {f1}')
print(f'ROC-AUC: {roc_auc}')
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.776536312849162
F1 Score: 0.7014925373134329
ROC-AUC: 0.7556628056628056
Confusion Matrix:
[[92 13]
 [27 47]]


### Random Forest

In [48]:
X_train, X_test, y_train, y_test = train_test_split(Xf, y, test_size=0.2, random_state=42)#

In [49]:
rf = RandomForestClassifier(n_estimators=200, max_depth=10, min_samples_split=10, max_features='sqrt')

rf.fit(X_train, y_train)



RandomForestClassifier(max_depth=10, min_samples_split=10, n_estimators=200)

In [50]:
y_predRF = rf.predict(X_test)
accuracy = accuracy_score(y_test, y_predRF)
f1 = f1_score(y_test, y_predRF)
roc_auc = roc_auc_score(y_test, y_predRF)
conf_matrix = confusion_matrix(y_test, y_predRF)

print(f'Accuracy: {accuracy}')
print(f'F1 Score: {f1}')
print(f'ROC-AUC: {roc_auc}')
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.8212290502793296
F1 Score: 0.7714285714285715
ROC-AUC: 0.8077220077220078
Confusion Matrix:
[[93 12]
 [20 54]]


### XG Boost

In [51]:
X_train, X_test, y_train, y_test = train_test_split(Xf, y, test_size=0.2, random_state=42)#


In [52]:
model = xgb.XGBClassifier(n_estimators=100, max_depth=2, learning_rate=1, objective='binary:logistic')
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=2, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [53]:
y_predXGB = model.predict(X_test)
predictions = [round(value) for value in y_predXGB]

In [54]:
accuracy = accuracy_score(y_test, y_predXGB)
f1 = f1_score(y_test, y_predXGB)
roc_auc = roc_auc_score(y_test, y_predXGB)
conf_matrix = confusion_matrix(y_test, y_predXGB)

print(f'Accuracy: {accuracy}')
print(f'F1 Score: {f1}')
print(f'ROC-AUC: {roc_auc}')
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.8100558659217877
F1 Score: 0.7571428571428571
ROC-AUC: 0.7962033462033462
Confusion Matrix:
[[92 13]
 [21 53]]
