# 2do Entregable del Reto
## Selección, Configuración y entrenamiento del modelo

Carga de librerías

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb






Importamos los datos

In [2]:
df= pd.read_csv('Titanic_train_test.csv')


Separamos los datos de test y train

In [3]:
df=df.drop(columns='Unnamed: 0')

In [4]:
dftrain=df.iloc[:891]
dftest=df.iloc[891:]

In [5]:
dftest=dftest.drop(columns=['Survived'])

Separamos en target y features

In [6]:
y=dftrain['Survived']

In [7]:
X=dftrain.drop(columns='Survived')

Escalamos los features

In [8]:
scaler=StandardScaler()
Xf=scaler.fit_transform(X)

In [9]:
Xf

array([[ 0.82737724, -0.54234313,  0.05915988, ...,  0.61583843,
        -0.73769513,  0.73769513],
       [-1.56610693,  0.59598827,  0.05915988, ..., -1.62380254,
         1.35557354, -1.35557354],
       [ 0.82737724, -0.25776028, -0.56097483, ...,  0.61583843,
         1.35557354, -1.35557354],
       ...,
       [ 0.82737724, -0.6490617 ,  1.29942929, ...,  0.61583843,
         1.35557354, -1.35557354],
       [-1.56610693, -0.25776028, -0.56097483, ..., -1.62380254,
        -0.73769513,  0.73769513],
       [ 0.82737724,  0.169114  , -0.56097483, ..., -1.62380254,
        -0.73769513,  0.73769513]])

Separación del train a train y set

In [10]:
X_train, X_test, y_train, y_test = train_test_split(Xf, y, test_size=0.2, random_state=42)#


#### Regresión Logística

In [12]:
    modelo_RL=LogisticRegression(penalty='l2', dual=True, tol=0.0001, C=1.0, fit_intercept=True,
    intercept_scaling=1, class_weight='balanced', solver='liblinear', max_iter=100) #Modelo de regresi'on Logistica
modelo_RL.fit(X_train, y_train)#Entrenamiento del modelo 
y_predRL = modelo_RL.predict(X_test)#Predicciones de los datos de prueba

In [14]:

recall = recall_score(y_test, y_predRL)
f1 = f1_score(y_test, y_predRL)
roc_auc = roc_auc_score(y_test, y_predRL)
conf_matrix = confusion_matrix(y_test, y_predRL)

print(f'Accuracy: {accuracy}')
print(f'F1 Score: {f1}')
print(f'ROC-AUC: {roc_auc}')
print('Confusion Matrix:')
print(conf_matrix)


Accuracy: 0.8156424581005587
F1 Score: 0.7898089171974523
ROC-AUC: 0.818918918918919
Confusion Matrix:
[[84 21]
 [12 62]]


#### Support Vector Machine

In [13]:
X_train, X_test, y_train, y_test = train_test_split(Xf, y, test_size=0.2, random_state=42)#

In [14]:
modelo_SVC = SVC(C=1.0, kernel='rbf', degree=3, gamma='scale', coef0=0.0, 
shrinking=True, probability=False, tol=0.001, cache_size=200, class_weight=None, 
verbose=False, max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None)
modelo_SVC.fit(X_train,y_train)
y_predSV = modelo_SVC.predict(X_test)

In [15]:
accuracy = accuracy_score(y_test, y_predSV)
f1 = f1_score(y_test, y_predSV)
roc_auc = roc_auc_score(y_test, y_predSV)
conf_matrix = confusion_matrix(y_test, y_predSV)

print(f'Accuracy: {accuracy}')
print(f'F1 Score: {f1}')
print(f'ROC-AUC: {roc_auc}')
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.8044692737430168
Precision: 0.8305084745762712
Recall: 0.6621621621621622
F1 Score: 0.7368421052631579
ROC-AUC: 0.7834620334620336
Confusion Matrix:
[[95 10]
 [25 49]]


#### Red Neuronal

In [16]:
X_train, X_test, y_train, y_test = train_test_split(Xf, y, test_size=0.2, random_state=42)#

In [17]:
net=MLPClassifier(hidden_layer_sizes=(64,64,128,128,128,128,64,64),
 activation='relu', solver='sgd', alpha=0.0001,
 batch_size='auto', learning_rate='adaptive',
 learning_rate_init=0.001, power_t=0.5, max_iter=5000,
 shuffle=True, random_state=None, tol=0.0001,
 verbose=False, warm_start=False, momentum=0.9,
 nesterovs_momentum=True, early_stopping=False,
 validation_fraction=0.1, beta_1=0.9, beta_2=0.999,
 epsilon=1e-08, n_iter_no_change=50, max_fun=15000)

In [18]:
#Entrenamiento
net.fit(X_train, y_train)
print("Done ")

Done 


In [19]:
# 4. evaluate model
acc_train = net.score(X_train, y_train)
print("Accuracy on train = %0.4f " % acc_train)
acc_test = net.score(X_test, y_test)
print("Accuracy on test = %0.4f " % acc_test)

Accuracy on train = 0.8919 
Accuracy on test = 0.7765 


In [20]:
y_predNET = net.predict(X_test)
accuracy = accuracy_score(y_test, y_predNET)
f1 = f1_score(y_test, y_predNET)
roc_auc = roc_auc_score(y_test, y_predNET)
conf_matrix = confusion_matrix(y_test, y_predNET)

print(f'Accuracy: {accuracy}')
print(f'F1 Score: {f1}')
print(f'ROC-AUC: {roc_auc}')
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.776536312849162
Precision: 0.75
Recall: 0.6891891891891891
F1 Score: 0.7183098591549296
ROC-AUC: 0.7636422136422136
Confusion Matrix:
[[88 17]
 [23 51]]


### Random Forest

In [21]:
X_train, X_test, y_train, y_test = train_test_split(Xf, y, test_size=0.2, random_state=42)#

In [22]:
rf = RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=None, min_samples_split=2, 
min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='sqrt', max_leaf_nodes=None, 
min_impurity_decrease=0.0, bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0,
warm_start=False, class_weight=None, ccp_alpha=0.0, max_samples=None, monotonic_cst=None)
rf.fit(X_train, y_train)



RandomForestClassifier()

In [23]:
y_predRF = rf.predict(X_test)
accuracy = accuracy_score(y_test, y_predRF)
f1 = f1_score(y_test, y_predRF)
roc_auc = roc_auc_score(y_test, y_predRF)
conf_matrix = confusion_matrix(y_test, y_predRF)

print(f'Accuracy: {accuracy}')
print(f'F1 Score: {f1}')
print(f'ROC-AUC: {roc_auc}')
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.7821229050279329
Precision: 0.7536231884057971
Recall: 0.7027027027027027
F1 Score: 0.7272727272727273
ROC-AUC: 0.7703989703989704
Confusion Matrix:
[[88 17]
 [22 52]]


### XG Boost

In [13]:
X_train, X_test, y_train, y_test = train_test_split(Xf, y, test_size=0.2, random_state=42)#


In [14]:
model = xgb.XGBClassifier(n_estimators=100, max_depth=2, learning_rate=1, objective='binary:logistic')
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=2, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [16]:
y_predXGB = model.predict(X_test)
predictions = [round(value) for value in y_predXGB]

In [18]:
accuracy = accuracy_score(y_test, y_predXGB)
f1 = f1_score(y_test, y_predXGB)
roc_auc = roc_auc_score(y_test, y_predXGB)
conf_matrix = confusion_matrix(y_test, y_predXGB)

print(f'Accuracy: {accuracy}')
print(f'F1 Score: {f1}')
print(f'ROC-AUC: {roc_auc}')
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.8100558659217877
F1 Score: 0.7571428571428571
ROC-AUC: 0.7962033462033462
Confusion Matrix:
[[92 13]
 [21 53]]
