# 2do Entregable del Reto
## Selección, Configuración y entrenamiento del modelo

Carga de librerías

In [14]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC


Importamos los datos

In [2]:
df= pd.read_csv('Titanic_train_test.csv')


Separamos los datos de test y train

In [3]:
df=df.drop(columns='Unnamed: 0')

In [4]:
dftrain=df.iloc[:891]
dftest=df.iloc[891:]

In [5]:
dftest=dftest.drop(columns=['Survived'])

Separamos en target y features

In [6]:
y=dftrain['Survived']

In [7]:
X=dftrain.drop(columns='Survived')

Escalamos los features

In [8]:
scaler=StandardScaler()
X=scaler.fit_transform(X)

In [9]:
X

array([[ 0.82737724, -0.73769513, -0.54234313, ..., -0.48204268,
        -0.30756234,  0.61583843],
       [-1.56610693,  1.35557354,  0.59598827, ...,  2.0745051 ,
        -0.30756234, -1.62380254],
       [ 0.82737724,  1.35557354, -0.25776028, ..., -0.48204268,
        -0.30756234,  0.61583843],
       ...,
       [ 0.82737724,  1.35557354, -0.6490617 , ..., -0.48204268,
        -0.30756234,  0.61583843],
       [-1.56610693, -0.73769513, -0.25776028, ...,  2.0745051 ,
        -0.30756234, -1.62380254],
       [ 0.82737724, -0.73769513,  0.169114  , ..., -0.48204268,
         3.25137334, -1.62380254]])

Separación del train a train y set

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)#


#### Regresión Logística

In [11]:
modelo_RL=LogisticRegression() #Modelo de regresi'on Logistica
modelo_RL.fit(X_train, y_train)#Entrenamiento del modelo 
y_pred = modelo_RL.predict(X_test)#Predicciones de los datos de prueba

In [12]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)


Accuracy: 0.8044692737430168
Confusion Matrix:
[[88 17]
 [18 56]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.83      0.84      0.83       105
         1.0       0.77      0.76      0.76        74

    accuracy                           0.80       179
   macro avg       0.80      0.80      0.80       179
weighted avg       0.80      0.80      0.80       179



#### Support Vector Machine

In [57]:
modelo_SVC = SVC(kernel='rbf')
modelo_SVC.fit(X_train,y_train)
y_pred = modelo_SVC.predict(X_test)

In [58]:
# Evaluar el rendimiento del modelo
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 0.8044692737430168
Confusion Matrix:
[[95 10]
 [25 49]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.79      0.90      0.84       105
         1.0       0.83      0.66      0.74        74

    accuracy                           0.80       179
   macro avg       0.81      0.78      0.79       179
weighted avg       0.81      0.80      0.80       179

